### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'swigged-llvm-native'

### ISSUE THREAD

**Issue by andyjansson** [kaby76/swigged-llvm#11]
When executing the [example](https://github.com/kaby76/swigged.llvm#example), I get the following error: 

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Swigged.LLVM.LLVMPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'swigged-llvm-native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Swigged.LLVM.LLVMPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_LLVM(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Swigged.LLVM.LLVMPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Swigged.LLVM.LLVMPINVOKE.SWIGExceptionHelper..ctor()
   at Swigged.LLVM.LLVMPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Swigged.LLVM.LLVMPINVOKE.ModuleCreateWithName(String jarg1)
   at Swigged.LLVM.LLVM.ModuleCreateWithName(String ModuleID)
   at core.sanity_test.Program.Main(String[] args)
```

I have executed `dotnet restore` and I see `swigged-llvm-native.dll` in the `bin\Debug\netcoreapp2.0` directory, so I'm not quite sure why it's not being picked up. 

Any advice?

**Comment by kaby76** [comment]
Looks like dotnet isn't picking up the dll, and I should update the instructions. Try first cd'ing to the build directory, cd bin/Debug/netcoreapp2.0. Then, run: dotnet your-main-program.dll.

**Comment by andyjansson** [comment]
That worked, thank you.
